server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: passw@rd

aws:
  upload-limit:
  region:
  key:
  secret:
  dynamo-db:
    amazonDBEndpoint: dynamodb.ap-southeast-2.amazonaws.com
  s3UploadBucketName: